### ISSUE TITLE
request: mandoc syntax 

### ISSUE THREAD

**Issue by grylem** [neatniets/man.vim#1]
Hi
please add mandoc syntax
Thanks.

**Comment by neatniets** [comment]
I'm unfamiliar with mandoc. Are you requesting syntax for the mdoc macro package? I feel that would be better suited with a separate `mdoc.vim` syntax file. I see that one doesn't exist yet for Vim, but I'm not yet familiar with the mdoc macros to write a syntax file for it.

**Comment by grylem** [comment]
> Are you requesting syntax for the mdoc macro package?

yes of course

>I feel that would be better suited with a separate mdoc.vim syntax file. 

maybe you are right, but man(7) files and mdoc(7) usually have the same extensions. And now vim uses nroff syntax for mdoc.

**Comment by neatniets** [comment]
> man(7) files and mdoc(7) usually have the same extensions.

This happens with a few other extensions, as well. Vim does let you inspect the contents of a file before deciding a filetype.

The reason I'm wary about adding it to the same syntax file is that there isn't much crossover between the packages and there would be conflicting results. For example, man uses `.SH` for section headings and mdoc appears to use `.Sh`; it wouldn't be desirable to have the incorrect `.SH` generating a fold in your mdoc file. It also seems like mdoc doesn't support `.B` and similar for changing the font style; they use `.Em` and `.Sy`, I believe; it wouldn't be correct for these both to generate syntax highlighting in either filetype.

An `mdoc.vim` syntax file could be reasonably made by just changing the syntax patterns to match that of mdoc. I have not personally used mdoc or mandoc, so I'll leave that task to others who're more equipped to not screw something up. If someone else hasn't already done the work, I may or may not, in the future, make a syntax file for mdoc.
